apiVersion: v2
name: jellyfin
description: A Helm chart for Jellyfin Media Server
type: application
home: https://jellyfin.org/
icon: https://jellyfin.org/images/logo.svg
keywords:
  - jellyfin
  - media
  - self-hosted
version: 2.3.0
appVersion: 10.10.7
dependencies:
  - name: jellyfin
    version: 2.3.0
    repository: https://jellyfin.github.io/jellyfin-helm