apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - image: docker.io/jellyfin/jellyfin:latest
          imagePullPolicy: IfNotPresent
          name: jellyfin
          ports:
            - containerPort: 8096
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"

          volumeMounts:
            - mountPath: /storage/config
              name: jellyfin-config
            - mountPath: /storage/media
              name: media
          restartPolicy: Always
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media-pvc
      - name: jellyfin-config
        persistentVolumeClaim:
          claimName: jellyfin-config