apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - image: docker.io/jellyfin/jellyfin:latest
          imagePullPolicy: IfNotPresent
          name: jellyfin
          ports:
            - containerPort: 8096
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"

      #     volumeMounts:
      #       - mountPath: /config
      #         name: config
      #       - mountPath: /media
      #         name: media
      # volumes:
      #   - name: config
      #     emptyDir: {}  # Replace with a PVC for persistence
      #   - name: media
      #     emptyDir: {}  # Replace with actual media mount (PVC, hostPath, etc.)
