apiVersion: v1
kind: Service
metadata:
  name: jellyfin-svc
spec:
  selector:
    app: jellyfin
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80          # External port
      targetPort: 8096  # Jellyfin's internal port