apiVersion: v1
kind: Service
metadata:
  name: jellyfin-svc
  annotations:
    metallb.io/ip-allocated-from-pool: default-pool
spec:
  type: LoadBalancer
  selector:
    app: jellyfin
  ports:
  - port: 80          # External port
    targetPort: 8096  # Jellyfin's internal port