grafana:
  service:
    enabled: true
    type: LoadBalancer
    port: 80
    targetPort: 3000
    annotations:
      metallb.io/ip-allocated-from-pool: default-pool
  persistence:
    type: pvc
    enabled: true
    # storageClassName: default
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    # annotations: {}
    finalizers:
      - kubernetes.io/pvc-protection
  adminUser: admin
  adminPassword: strongpassword