{{- range $index, $stack := .Values.stacks}}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{$stack.name}}
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/kenadaddy/turingpi-homelab
      revision: HEAD
      directories:
      - path: {{$stack.name}}/*
  template:
    metadata:
      name: '{{`{{path.basename}}`}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/kenadaddy/turingpi-homelab
        targetRevision: HEAD
        path: '{{`{{path}}`}}'
      destination:
        name: in-cluster
        namespace: '{{`{{path.basename}}`}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
{{- end }}