apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  annotations:
    metallb.universe.tf/address-pool: 192.168.68.243
spec:
  type: LoadBalancer
  selector:
    app: guestbook-ui
  ports:
  - port: 80
    targetPort: 8282
  