prometheus:
  server:
    service:
      enabled: true    
      type: LoadBalancer
      port: 80
      targetPort: 9090
      annotations:
        metallb.io/ip-allocated-from-pool: default-pool
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    labels: {}
    annotations: {}
    existingClaim: ""
    mountPath: /data
    size: 8Gi
  alertmanager:
    enabled: false
  prometheus-node-exporter:
    enabled: true
  prometheus-pushgateway:
    enabled: false
  serverFiles:
    prometheus.yml:
      scrape_configs:

        - job_name: kube-state-metrics
          honor_timestamps: true
          scrape_interval: 1m
          scrape_timeout: 1m
          metrics_path: /metrics
          scheme: http
          static_configs:
            - targets:
              - prometheus-kube-state-metrics:8080

        - job_name: 'prom-node-exporter'
          scrape_interval: 1m
          scrape_timeout: 1m
          metrics_path: /metrics
          scheme: http
          static_configs:
            - targets: ['prometheus-prometheus-node-exporter:9100']