prometheus:
  service:
    enabled: true    
    #type: ClusterIP
    #servicePort: 9090
    type: LoadBalancer
    port: 80
    targetPort: 9090
    annotations:
      metallb.io/ip-allocated-from-pool: default-pool
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    labels: {}
    annotations: {}
    existingClaim: ""
    mountPath: /data
    size: 8Gi
  alertmanager:
    enabled: false
  prometheus-node-exporter:
    enabled: false #true
  prometheus-pushgateway:
    enabled: false
  serverFiles:
    prometheus.yml:
      scrape_configs:

        # - job_name: sonarr
        #   static_configs:
        #     - targets:
        #       - sonarr-metrics.default.svc.cluster.local:9794
        # - job_name: radarr
        #   static_configs:
        #     - targets:
        #       - radarr-metrics.default.svc.cluster.local:9793

        # - job_name: kube-state-metrics
        #   honor_timestamps: true
        #   scrape_interval: 1m
        #   scrape_timeout: 1m
        #   metrics_path: /metrics
        #   scheme: http
        #   static_configs:
        #     - targets:
        #       - prometheus-kube-state-metrics.default.svc.cluster.local:8080

        # - job_name: 'speedtest-exporter'
        #   scrape_interval: 1h
        #   scrape_timeout: 1m
        #   static_configs:
        #     - targets: ['speedtest-exporter:9798']
        # - job_name: 'nginx'
        #   scrape_interval: 1m
        #   scrape_timeout: 1m
        #   metrics_path: /metrics
        #   scheme: http
        #   static_configs:
        #     - targets: ['ingress-nginx-controller-metrics.ingress-nginx.svc.cluster.local:10254']
        # - job_name: 'prom-node-exporter'
        #   scrape_interval: 1m
        #   scrape_timeout: 1m
        #   metrics_path: /metrics
        #   scheme: http
        #   static_configs:
        #     - targets: ['prometheus-prometheus-node-exporter.default.svc.cluster.local:9100']

        # - job_name: 'metrics-server'
        #   scrape_interval: 1m
        #   scrape_timeout: 1m
        #   metrics_path: /metrics
        #   scheme: http
        #   static_configs:
        #     - targets: ['metrics-server.kube-system.svc.cluster.local:443']