config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/kenadaddy/turingpi-homelab
      targetRevision: master

applications:
  - name: guestbook